---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-ddns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: cronjob
      cronjob:
        concurrencyPolicy: Forbid
        schedule: "@hourly"
    restartPolicy: OnFailure
    image:
      repository: ghcr.io/onedr0p/kubernetes-kubectl
      tag: 1.28.2@sha256:042bad029205e40a9c0e0f3150ab173c61cbb69eba326dac425e4fc419b83963
    command: ["/bin/bash", "/app/cloudflare-ddns.sh"]
    envFrom:
      - secretRef:
          name: cloudflare-ddns-secret
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: configMap
        name: cloudflare-ddns-configmap
        subPath: cloudflare-ddns.sh
        mountPath: /app/cloudflare-ddns.sh
        defaultMode: 0775
        readOnly: true
