apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:TlMdaCQ8p2rNz8S9p2Ha0d0=,iv:CniVK6lcPwi4PHpa9QawweyK9mzn5uJZVnqo1TE3ZFk=,tag:JVMwBIWsz2X/MAxheFUXNw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:FbTpEcNwQMNmtvjGvqIyDXBIuiB74YFTUq7dXiBqJAX7B3nf9A==,iv:kI06d74KAE4p0pX+vnCf+uhudbERTM5jQqC3hxJVz9c=,tag:wokLLFD//MZH0A48Y3QFGw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:HnA4utSfsnO9tPy9I7/itQ==,iv:FBlbbhlac47/NF/Xza3cjb3qvs8VrecHuCGne2bn11o=,tag:QTlbWd8TTcuekb/mlULqDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNWoyN1piei82Q0diV2hN
            d05mNDhDcGdkZFg1NjhVa1lobTFPMHhha0M4CjBxNVU5dUlyZVovYktUQ01ZSnVU
            MEtkSDJ3c1VWS01IVEhPNmFyMUt0SUUKLS0tIHZPdkRiRWVLN2E3TW9KNE9zYVpw
            cDZ0ZEMvUDlsWHZIKzcxdm5FdXVveG8KCA+vVh02CxHP+sq8xEi+t+PwdLkrYihH
            6qd+QrPLbejlHdUxfGg1Sqps4fU65Q4zzzvczVpsyBz7bFLeuice5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T19:05:26Z"
    mac: ENC[AES256_GCM,data:KxitDKd+B3JjCcoYsak7U4vUGoFBs45rbHAEks+bJxTMbkAjQeTnWvKq1Bf5rU38QzUQz0S/G0+eeau5SmqTww5Ne8WalA61YSGPQ5ow3odsTpyn+ugH7ejVNdKO210cTRNQOGAtLVVGvk6ivvMzrlhvm8LjPUr5Aeni+MeBEJk=,iv:xgz/jjTQLhJY7/grzwdyF4Qq6vdJfpvKywYHtabdn1c=,tag:5lwy0qd4+MqapK+obEKC3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
