apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:18dWdschosiN20mniosXIlA=,iv:5Ay9+wfPd9m2KWIC1kd0azfkk4aKy3Qq6kbR2zYivE4=,tag:XC1SoarmRp6b187q6D7DPQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:gVFSc7HWlk6iTYFXL9JecGPOkID/ZY1zBxNxx5DhWIT00LDU2A==,iv:8vhn7t6JjGcjTYMH4y4lqFuBiF+Wksogx/LHkx3d6e0=,tag:BjxBK3lVbzpS4oK1k6yObA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:C1btmgvtl/iLUD5cLb0OWQ==,iv:g6xOMVEdifDNuIqDNHEJM9/gx/TcjbjS/oyyGDbLgYM=,tag:RwCnZMI3la+EnZWrDtXCEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOGxtTXhmTGF0Vk5xQysx
            eTR3SlJsSEx4NUVLR1ZPVGwzZ2pORnhUNDBjCkVNQW5EUXV0MHEwaVRIQnJ2eTdX
            Y1lOU2QvTDkwb25NU1VNaHNCYTFVcTAKLS0tIFRnTXZRQWZTUTAzWVNSU3d2UGcz
            QndrTkFtVlRaTHRWdXR0SVdtcSszUHMKanK4MbyETR/n5Jszg3Vwm/F06MxVL9LC
            liXdhy7nQ6c6q/Ejz8eo/Ev/ISfyO8NtTmlI2oFrkfXQ5EmeZRxJEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T19:05:28Z"
    mac: ENC[AES256_GCM,data:AcNrsIRuGXRmCwl6YqTmjHbuWxbWIi0RvnWXtOOQtuyA51pKC7teK3CiRIMHUm9XzWPlYhoDuIPMV5fwl/sB2dRChSHW5g0SK2ZtsLZGW6JzlLibWhkzwYOMwlsiBIgaHxzawM9L6ZJTMGcJBRX2Q94LIt2CEUst/tYtPb88yQ4=,iv:x6KuOCkcuVT+M161atncCv28COWLq4GW2ftiybNJ6lg=,tag:MvuU0pQf8OC+ze1j4lJMcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
