---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi
  namespace: networking
subsets:
  - addresses:
      - ip: 192.168.1.100
    ports:
      - name: unifi-app
        port: 8443
        protocol: TCP
