---
apiVersion: v1
kind: Service
metadata:
  name: confluence
  namespace: networking
spec:
  ports:
    - name: confluence-app
      port: 80
      protocol: TCP
      targetPort: 8090
  type: ClusterIP
