kind: ENC[AES256_GCM,data:8ROPFSJH,iv:+vd6oG50zX7O+w7u8+I23V4rMDyKnZejJZ+5xSTTsUE=,tag:tNTDpS6ybITRSrXktsbhsg==,type:str]
ansible_user: ENC[AES256_GCM,data:x1VFJfN6XcU=,iv:8l5zaaN/UST9Tszx5hlSURgfu/OkvLj/jz6MrrJ4ddk=,tag:qwLWG0Za0siDj445of7v7g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8jJP/J0nkAA53hPdsg3mvyZo,iv:GRbCRIxpr9uD2ujCYqJe364MK5Vz4ksK/Z/Q+6guXkY=,tag:+dn7oQpsr7c7gXyer9SN/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacTN3UTdBdzQ4NTJJQ0s2
            bitRQloyMmNGSm9obXc3MVl0ZzBQTWJET1dJCmh2L1ppVlU0MXFNenFTZlpvY25L
            TE15ejdrUytMQlpVd3gyYUF5eVN2SEkKLS0tIHE2VytGc2M2eVJOMEdWajZFcW1h
            WTVsd3ZxYTNRR3hsclNxSzlibEJ4dFUKCenyQXD24mg+WeHUl5m9hJFocnG/YzsW
            FXKY3PrfrrWIM6DwOgiczmdzJRff426uFYnXUdwrbTDcBIjp70RMxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T18:36:25Z"
    mac: ENC[AES256_GCM,data:oRQze/jSQNV+TrVSucbUQuSiw0oDL9a+CyQyHh7jRXtd0LwfNSHjuPUQ61KnIKdnpsIuCPoxwTJ8IatFArlIgABrFWDXSf65CX2WM9JOeONc8VhY3Fc+IsIwUvgMFFhZaNdfajx66vxXOnIfs00GKR7EQTvlaTJtW4XVHON5XRI=,iv:16IRbkNDcdJlEw4DtaTJAcUNL9kHKHgKAlZjLIhU+DA=,tag:WnZyJguxVQt/mM6I4x+e1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
