kind: ENC[AES256_GCM,data:rk+1TBkm,iv:LtQrH7bRhVtJx8Y+r6qJlbYk2VVoMVdipdad6Wjq9jQ=,tag:+zLkU/y535d7m81ZfWDmeg==,type:str]
ansible_user: ENC[AES256_GCM,data:cRtdki3zkdw=,iv:zSgmpSx0e7lWEyyKDN3RrLE1YoYGyv9skzHIsyQPyrs=,tag:dlU9quCrBZKq8uMvlgBfzw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:UkaeAzENKfkT2kuFSAHjKPTw,iv:UhWcGDHiBhoOljVcv7w9RswlqNRxcxY7ZotX8mJv/s8=,tag:yC+Sc9UPrbQwH8fHVcDC8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdGN1MVFLOUUwemNtaHhl
            RnBObkJ4T2gzUDRVOTN0OVRXaWhINHFiS1ZZCkx3OG1XdFBJUHdNSkhRTnNSTCtx
            ZFA1eFFnRzArZnpYU1grYTQ3ZVlvR3MKLS0tIDY2d251Mk1wQ20rTUZ4VzRFandY
            UnpoMGE1RlB4WHV5WWNtemQrL1pjYWcKqxcVM3P9++Ot1LoBcbVG1mzGd2Cs8M4i
            lxKX5AAP/8bsiyVTffOYghm7xUVM1IYA8zV2W0/ge9f42/dhziGgJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T14:50:36Z"
    mac: ENC[AES256_GCM,data:Uwi76VEC9GkgiaMR4Jgapy6SbP0ZDH86yWtaF1LMg8ict70y8RBshtVr+w2pFSeWxlZTu9WrkqHCHAraMPR2PJefrW8FMjjN+xaPl6hqRTASt2YgPJUeVZ6ihVZPi2CMvpfzyCRLHYnt9NXYY1zwaZh0n+KUxZT9mlXeUSdjrc8=,iv:riNVStaHcvfkJpb1PXxQwzaGMsREIb45DI2IOlrt1VA=,tag:Uh44KcgCgoITbfoi0QaeDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
