kind: ENC[AES256_GCM,data:1ItE898+,iv:XSO1emVqTcs1Dzg+pA2XqMMBtzgUlDXcJdFgTnp3qqU=,tag:YmlNr+Wv6w871Mt4Jrtfng==,type:str]
ansible_user: ENC[AES256_GCM,data:UmINjjrklFc=,iv:GPzPmoUSPJ4mIRtJpBbNM+3J3ITnGZNW98f5dpUmoLY=,tag:wCPcCPSizxRFtG5qeSanug==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8QDy9FVLussKVWwvIBZt7FoW,iv:+gAjmeN8oGjrEG8PMy4OH5lotu5eG/ASkNdH+mrD+S0=,tag:SPFrZPzM0FRKbBeGZovm4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENGhzbE5oMlBhLzlXSElQ
            dGxLVmhYbTNMRU5pallTL0FIRUlKR2pDU2pjCkJ4Z1JseS9odjErM1hKWHVQMGNF
            VnRHVUY3ajRNZXp2K0psYUhpZWdsRk0KLS0tIFovbG92elRoWGZlRnY5Y0VwNGNt
            QnowZThJcnNDSUt1cFBqZUlQeFVkeWcK3uQ6/2EWo8jQAU2zMUQc//5ZpJWyW7ju
            i8lI7Ryj52kJUSn0bvlatg3xVtnX//1Y8GEO0KOwvyjiroYf8SLAJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T18:36:25Z"
    mac: ENC[AES256_GCM,data:UJkZpe+bAz3XGiqWSaWoUFDaKUv3vS+OrZ5WbLv8iiybiydSHftFsCl8n/lYLOxvboMMDzw7s89frIecXp3DsVq3n53jZPX4bgp/vtHh/Orkaglz0zGuNfWdq4RI7o5hZfGDz/mg6/04Rs8P2DDyFtDXGWZyULl7jBSCoBAVP6c=,iv:5m3Af3FoEIygZa/Pw5bOBvLVkqjYPTyp4P/YRfOgP1M=,tag:Ud0BQ1QYrwFDtkZ0HQXxJw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
