kind: ENC[AES256_GCM,data:RRZCcsSw,iv:Vhyny3YcGOqQUG4/C3UNviqekSC9TOyneom9/nAp11c=,tag:rNv/GC978NQfesaCysihOg==,type:str]
ansible_user: ENC[AES256_GCM,data:xjOYAjSIz54=,iv:cPVFkBlsXkCiOO0vld9tmLpb485glfR0M56sT40yU74=,tag:HkD6Qv3Ng7NHpQjswv+KHg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QCUPYZ/up2ou30otvAuIES1J,iv:wuBaPeNCx+XKnnOshQAGL9cnrARqq4/EU4QQ8rYA2qA=,tag:5AEZyKkH9XrZ/LdXLeyDvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OWZlenVaUkpmbldNNW1Q
            Q2ZSN2NRZWJqOXlSTnl6YWJIUFZmdVlQa0ZvClVxclp0clZQYzB5Q1dZVHd2UGtE
            bjA5cGZlNHBoMjVJZUgvS2JYby9NalEKLS0tIGFONnlDVlVLOHFzMzJ3cjY2bFpV
            YjVCOVV3Y3hSK3ZiWEo2Vm15K0RJZTgKrBjWABfTfHJXiM6e4CXr6cgBgR3zmUTW
            SBKacuLZJ7ajkM046z60b2Ms0CWlIN9h3CCJCDTx7xsCvwSo1ofvig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T20:38:10Z"
    mac: ENC[AES256_GCM,data:y4D2Vylr/jNoKYyytuBgVXCacRqgL6Yvg18gjYd6+s/h+P6/WrDZpF9KcrkihF7kjhaEbshr/QrIVOCW1XviPwZNkXp/7cBPvggAGWib8qYZLDKN8CdGrddn1sQDbhWegdJy3du4MawZCeZIQ4m8ONiL5xfZ/1gY2LGz3H76z3k=,iv:F72R6jviOPHxcZE0fp4QTK7Kgo0mL4b9iAg0PnJaM7w=,tag:vQiC0RK6PaBvc7WszjDzRg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
