kind: ENC[AES256_GCM,data:jYwD1zQ1,iv:JrgbOvESlB9sk0awITzTu1HM+q1LohaYTfk6EF9cKVI=,tag:Y+Z+n19srXvoX0RXW8l4sg==,type:str]
ansible_user: ENC[AES256_GCM,data:G+fskTCL/+Q=,iv:G2JHQXiWl2QMk+WjqFz4Re+T8/E8btiJQfLJunOnU9w=,tag:gowdm563jVI2rcv+mOd+wg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:aD8l0pMbJfNU26eQPgGlL77s,iv:pN3GkjI5ZN6IgoMjUYzOL3OHe9wj/93kDid8DA85KKU=,tag:WkGcA4j6N2S7+1mEQjyCgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbVA4ZU1JZkpDNUhFOStO
            RHdwY0lHRG5RWEx3RlZRODJWUklOQjJvYkYwCnNmcGZnSER5U0NpRExJc0tqTlJP
            dFpsZzd6NTRuSkxlZHVmc0FqSkJpZkEKLS0tIFRvRXZXUkhnVEdWcmZYa3pwZG9r
            dE82SEVCTnRGaGovR0p0QTgzMFVhOE0KxxGPMeEQ3RAl3FCbNKjZSyqtHxfcPAE6
            6JzdUR+AEMeUlgNV37kepHFRmELfkwEQTziU8VhY2PeBXJApkFbZEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T20:38:10Z"
    mac: ENC[AES256_GCM,data:Q+NkYaA/o2QvVlGl+I4aa4F9D5NRqVbW2CGTVHHHGCm1zQrh/4C/vspF7LRVzfnkg1SCm7z15VtnKvvIU07IQzhEpKKQBWhvs24TB00OnoqSPuvDwiroiuXnw6Dm8qD6noa+JpmVT9/Ehj77Jxlt92FtgTPWiceiuuV23FeRDaM=,iv:o43fJ/Qh9D5Jb6sXFkHJPax39S4IR5V0GwPXvIdY4Kk=,tag:OopJC7JPVJ3kjkVnGYmsbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
