kind: ENC[AES256_GCM,data:4YF63i+T,iv:nMm99er8NiNwe/9WDn0JnJ8n15bDKGrf6VfZcC5KfG8=,tag:PzUrNYxLtMjXzL4sxkEfmQ==,type:str]
ansible_user: ENC[AES256_GCM,data:bG85gGeptIU=,iv:bJ1F6CNNxjkvyqA0QAE4UM7ZtH52yStE0Tz4ud4XLcM=,tag:ZYZ0hfMDBLMpFKY8OXXGxw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:YaPFHjmS8Voyvv62SGlk1BFH,iv:yG5tl7PrBG9dH6ECGU2/HTEkAlu1pbbR+Wa6Paj2yM0=,tag:CT7QjEB7V7jMToisg99bTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6am1tZWt5Z2RYOFlTVDM3
            VWx5bGptbERoQ0YzSmd0cmtCT3JGcGwzYjNNCk9iQVJEc3FyREFHaURndHFqaVhL
            dVUwd1RQQW9XN2pRcEFEM2FCUm9jU1EKLS0tIDRPczJQNCsvQjdmcC9DUUxDdzd1
            WlRxZWhnL1NFblByRVNVek9PYlhPQm8K877DjOvqmMkGza1swKGuKQgZ74pRPAPR
            +D4Lnau84EP86fm/fAjsbMDNNeNWjVf6JkEIWClNAaZLU+M4eVb1kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T19:57:45Z"
    mac: ENC[AES256_GCM,data:jqKaADMV8OufK9T+uu++TB84RR5/p+2ECoYb/qPFIGrSXCEwpn+p7FXomQLfb6G2kKBEcvDf+c5Nzyd5rBaZXQ9HX7Rovt0G23flvo5eXZHTr0LvkJwffdswtl3fzBsQWepNCqkNoXL5XoLC2KpUSZASySRaWY00w3bSkjxcwww=,iv:z0sAkrwgknIYNP3r0n8Lu/q087TblpIyTqaN4pOCpA4=,tag:RAay+kdRmKqcl2pfR3kT2w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
