kind: ENC[AES256_GCM,data:3cAfFyht,iv:DKTbOLwReBTkBViOd64Ka/9EdebDonEqJtuR/aa1qhY=,tag:y4Exb1kbKZGVdv2AT1Qu6g==,type:str]
ansible_user: ENC[AES256_GCM,data:sth7TUAtifo=,iv:b1C2uS1HMR6KuoBMNyYldC7d9zGSAKU4Sm+kwfPU4JQ=,tag:ktT1tdAlQNTW7ZBIIVB7EQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:IlSRROA6qiFUSDkSNwfPfMhi,iv:qbcniI7va2Cx/oBUzWmNQPfD55GYo006LDlzH/EeqVk=,tag:7k8eLK/CoJx506YiqT1mrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d3hYYlBJMUhFZjRqYUJL
            cjZyV3UzT2lQdW5kd2FpcUN4WFZzd3hJU21VCk1YTlRJZDd5UHZOK1pWblBwTDZr
            UUhlK290Q1AzdFBvT0ltMjVDZDZpZTAKLS0tIGJUZ2pBTnFPcFgzcHhLcUVtUHNO
            Yzl5aWIwZXUxQ0EyVjBzSVM0dlp5dncKtfhUiLpk3BFc77bjuT7d8g+qf6+QcS9e
            S62DUQmqFAAus0dXkhQ3SoLvoma8SGqwBsOxWMtCgP8WH8mpHwmaEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T19:57:45Z"
    mac: ENC[AES256_GCM,data:33p63iXvVch/bHPOcjhG+3QtWmf50U5kA7xf6T5fEsMyKnui/F16cgVYxmiECRLyS5vJfU1Xoo7rPF5rXr9xbxiFTDfkh2xkUUwE6oA/0MAsXETe2ozn631VaW+xrVFKhlBU1x6KVQ6dK3LIGVn/ksUlGkhqyUem5VgUgSy6Kp0=,iv:o6lL6UwDeDeAz1vrVqmraLIihVQ5NaviCXM5po+qSQE=,tag:ROC2CEoa4fqMKorpiDR5oA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
