kind: ENC[AES256_GCM,data:Dx3H9SQ4,iv:szod+2NdQ+cjeVcHdZtA8Mmi8qOlQ9a0xlwkvAmGJxw=,tag:HGqP9OF/Hw21KmG0rApXdA==,type:str]
ansible_user: ENC[AES256_GCM,data:Yrq4/RTPMxQ=,iv:K9WkpNEbTXGCbjq8Tc6yOBWJ00+P7AeAEVm+QYWn5sc=,tag:fcdHHyaO6MLn+AlN+O/FBw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:NoDOW7E7yR7MkWtFz6WE/Ft/,iv:WzsbONE/rCIAmbMP2AGNhf6HHEyUmIpcRU0A9yys8tQ=,tag:gVNM0cvF44tSsNV0e4sPTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NU43Q2VhUC9hb3UzeCsz
            UjZXUktuQXhjNTJXbFpEcTZ5ak44NWd1SFZFCnRqanMzVkRKYUZQUzdQdXphYnpk
            ZEY5b1VrdDIxL0RDVkhXamt6R2VtOUkKLS0tIHBqamY0dzRkSFBoTkYwMy9zMWx3
            Mlg5YUhRUjU2aTBnRFl2aUNuKzkzazQK4qUgNZ4gIed4ZTYmYTfrGaDZ0h4EkWq0
            xR1EZTeH3CBcEuqSJ/Sfudl6rZDdea7jF576FZQsc92471Sxe0roNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T19:05:26Z"
    mac: ENC[AES256_GCM,data:NkAaQ+AZhoguVzwM2IL4wiFIhYz2mKvaw8dDms4wTN136fwtXOrbd4kkvta1MeL1by+tAwSitTusl3Y6U+YvHzg6RsRqvyNmIVRbn7eAkAiydwD6aa8r9T/KRLLd52cQ+iu+z47rs6+EwOtGK8deLeqUIgJYiTBymKWwok+z22k=,iv:ZSu3ytEhU8E6Fuiof2fCLYzmAvhR191bOz+Am8LME4A=,tag:+ZK9acbHwm47HWy0Wtl2Nw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
