kind: ENC[AES256_GCM,data:QnUpvAsB,iv:t/730/ruieoWmcMSlRq5TFNltzWXDkrd3E4B2BV34Xk=,tag:VSyjkm8PFb3tmFB7KCIRsA==,type:str]
ansible_user: ENC[AES256_GCM,data:bv+uLeg0YOE=,iv:r2UneRrB9fKskLSk6EYfUc1g6EWaV3hp7e6EjW2KZrY=,tag:WiAr2YtmAqVazyUjWUZzUQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:vwdOVCgnAtYRTsZug2Klwrll,iv:8FgJgByXdz3emew8qHWhQLmN+dG+fYQ83UGTYyWBToc=,tag:0Igvi2wVxlH5iM6vEz4vcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SVRGNlN6VHhIbkNoMTh6
            MTVVNXloVE4wTW9TYndIWC8xbkg0WktvNURnClpkc3hXclpjdGt5M28zYzBTN0NT
            VUVJR0lPaVVMQm5VbVp1Qm1zdHUzancKLS0tIERZWnI3dlQwQjZIVXFZYXcvY0xB
            NTdsdGR2aHgzZGFrNkZYbWV2K1kwcTgKHDLn+1XaFnnrZ2kiyGL/wY6ltfWUTUtq
            puFbcu8D18m9z0dzLecjqFHfpS/N3MyqP4P7sPTgbb7IjXe3j5Frkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T11:18:38Z"
    mac: ENC[AES256_GCM,data:n58UOD5J4WtjGjVqaH4A5XO2YxQbemYJDzLGelWjiy7CUqYdrG2W64CVKnFNT1zMFVDHBgfLGsobwwNohu/RUSPM1j9jixReUe5jkEh73ZERJQslbV8nktOBWeHxuxhHsW235nDVNM8Dbrv+YCOtrPjfPzEKOnft98uxbQk/lAw=,iv:r6es6eXlE5rH8/L8zOrcFnMmxazBwTgmFZmGNfKEnh4=,tag:H6Sq/+78CHGflXPyw1piJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
