kind: ENC[AES256_GCM,data:UPfbeJRm,iv:fUCesb+zZWXy/KKsbrmufdaQPua+JLlULhDG4DC4Lww=,tag:yMW6VVounLJMDgx2u7Rb/A==,type:str]
ansible_user: ENC[AES256_GCM,data:F/36m3SYNO0=,iv:3p4qSTjuyoFjkgNdDyLOWM/8QY364x05639aqvAAtik=,tag:DEsrm7RqeYGLRgDwgpCAig==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:nKoELUV8+lRIK/mn5dIfIror,iv:xyQaLd27DW31LK8AszSGAruXL7ni4kI4CAHkpqgcGxE=,tag:aK2OgGUBEe6Ck7UnQfl3WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWFZYMjN5OG1NNEUwKzdE
            SkkxVmF3NEVHUFQzWGFOTi9LTlR3enA1WGdJCmR1V0xVV09KZ09kMW5aTThKeTM5
            MDN5OGlYTGVKNFhSZFprVkF5YWlxK28KLS0tIHZkUlllRDdlOXZQaEpJNXBINzl1
            ZmNoRUNZTmZocndjRTQyN3RjWXN5UVkKQzQTKN2Tgnxy51jO3M8kqKe6xwHFLrdA
            5naQQacbT7G31+onsdwSubY9KJBMwGKRJuLWTcbeIQmy2crWtJUv3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T17:50:35Z"
    mac: ENC[AES256_GCM,data:I3GUR7mqH8ctVVZS5YCEpzwsNG/1hhSlPBEMdS10RfBR69lCPUWks4u1MaJAe+3i4X58XXPPZ9QRgWfU1yVXZXrQ+vSp/fYESjE5P/yBJazy57GK3o12U1oZa39IyaGwFNnBll6ss4VzJeWr6yFeBPL4LgZcVs3OblKuTvkfuiE=,iv:IanbTaoBtoFc4bESRA3l6POgH7BuvliXe4tvtylLXsY=,tag:6zpnqwoSSaZDLqtRNv8MoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
