kind: ENC[AES256_GCM,data:kS/kZsOe,iv:WTxC1dmLw8T5vsoCCO3JfjbuCaqAl3vs+yZhl6TWBYo=,tag:sNk2L1tZvYLO5ScNlmGb8w==,type:str]
ansible_user: ENC[AES256_GCM,data:8WpCUWLF/zM=,iv:NdA703nsYQC1/R5NpaxI7ld7A6whDzR1fWjHQBlt+FI=,tag:ibXJp4gBtLpUhHXMjV1WAA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jexMLDk2Wa3RYIe09d3KO5/3,iv:X6SgyA/pj5n4wBpfESuEnHvad4v4HYHrSnFnQGV8dFk=,tag:2EWJeSkRuWZLBlPbG+IX0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZDI5a2x6NWgrUWlpMG14
            YTZ2YjNnNklvSUNjTStaY0l6OVY3M3hpZkVJCmZtUWNoQkpTS05iVFoxQk1IOEE3
            cUFBZlRZZUFtRm9sMjZ6Z1dDSlByMDAKLS0tIFdKWUJWb0VwOEw4amJsLzEyY2tU
            bjJrK1hvVzE4K2hmcmpLQTA4K3JOeHMKwQnjI3STDPhQ9hvokH3wDHiaPv3fUsmE
            CodSIchDbvmwDL3lsc8n7by7NfO06+YhKFilI6hXTRYTxbz6/VOd1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T18:36:25Z"
    mac: ENC[AES256_GCM,data:IynEuBs3YDZdY1c9aeiT2bdG9BbynKXjp5i4xIMeq8DT9Rg0VjUafBpEH8BSpcP35N54khsv5mocK3As9YKr8oCiX3bM7Gvhsvv6RK6Ig7cfSngeNBnBb+JmbnMRAavnpOTpPyY1L6jA9vDVEfl/IijF13a6qamQ485salEX5/I=,iv:j2RImceX6AYnu4AwCULrARWsOHb9n+ov6l489/PccPU=,tag:/pbEntNzkq/hOtu5PaIpDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
