kind: ENC[AES256_GCM,data:UnXGTPRf,iv:nABhqYrgg/rYxS4d5tfVBG6jTEjDtcn80Y0xTcK+Vg4=,tag:j6Ejs5bHmQe/w9HE+PkCUw==,type:str]
ansible_user: ENC[AES256_GCM,data:XeQpkU/jomU=,iv:yn7GzcPUEjkkQzpA6vlEjYUPFJn33+XmY9Iq1muimLI=,tag:8/okHGOOgW/HFrhCmHfOfA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:g6hfm1IJnj6I2XHbgUuqb8Vi,iv:EWBDanytd1H2zfYQpmVeFM4AFqSGTIU0ZZcGG013L4s=,tag:IXCx7XFvpfCZe0mkZyXFUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ1RDQUswZW1aS2xDbjVD
            TUlmd0lhNCs4bllDQUNidTRINExzMG5DQmk4CjIvbU9TdkJ1ajdtSmRDL1V2ZXRQ
            b2FaQVcraDJBMFZIK3lpenY3bEt5NEkKLS0tIFJYN0pSeTdyUFNQVkxuSWlSdSs5
            SVB4RzJNZG05NEJqWnhVNkNmeCt6MWcK1wjLxDAz7mWXTVgePh0VZYdCufhjWlW7
            RvPTuliWCqM54VThRjmobxUNZx34z+fwBr/TOkJfc6eAnt4Avwk5Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T17:19:03Z"
    mac: ENC[AES256_GCM,data:LtDpy66kVtsk5ijMGWjrLkRgX8hq05jCQ1x+WTRjtZggCot3u+C83WjT9ziiYC1UoxV8NTIpc4AuCr5o7bVt/+UGZHpThZLLzqUZcAJ6wtB9GnBZfEF3BrA0AaV8s90wxOGcm6hw4jIuAtst1UDiJKHcowhXtgzNARrl+svRycg=,iv:KV+Bs807qIr58fBVmFpN/llIiP3t1blAkDxvM/HvqNQ=,tag:9Z2cV0TBevWNusW04Qdjig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
