kind: ENC[AES256_GCM,data:xB+G95hS,iv:kHOUIHKndJAn+YvgMHPv30ur+zh1IANb7FATA9RqUaU=,tag:w7Fg7meBhCeyyp/7iD7u4g==,type:str]
ansible_user: ENC[AES256_GCM,data:an5iDpJOk1E=,iv:fNhKOXaqBkajRA8J/pskWAwMwfctPUtM3YBbRtdpgnQ=,tag:yablVFsLmoZRdYO3oNlARw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:RQGjfc34TsNc11I8Z3ObxhnD,iv:SWORuW5PXYhxfY6t7y8wzjPRrRIrfz4NtVRzL1iSSHI=,tag:mhKx3bJADtfISGIDbm62fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cDFnT2dUelFFN2lZVStx
            RCtIMW9MOURrMGhtVFRtZlRhRUl6My96azFBClBIWEtaL2kwbitYY1FXNlhTOW5C
            NEdGZVI1cDFIVkh1S3JRVVJuLzVrTW8KLS0tIFVIMkF2Q1h4Q0Zoc3pVSDRqTi92
            eUNTY3lxWGJvMWU2SWJ0NlpkcjVZd2sKUZ249B5HpuBG9L6eLODtVr/I0wMgFu+k
            WZ4vCO6uXZdZhebsjA9Y7lxGsDOcigczDYlPxE2kLkGsSpYCxkeQVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T16:01:02Z"
    mac: ENC[AES256_GCM,data:a5beI15tFH05bLqg1T8Irp/6nZgZC4t0+it/VCNHWKRoNN+AheCFNf/Q2fBOyIA5+mmuQ3LQdGrc5mbZ0XZoDaaeIb0brw7n89XXIJ+PgRJRVpldfG4lmj892S14suQM7kpX26frWGircKKWVICsJXQgXQA+z78eO+Ui7nHoZxM=,iv:L2okx+kuXeXRkzEIHkycf63Ayygh0utLKHMG4L4jWe8=,tag:JDHIIcHwTkqzr8gsctGByw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
