kind: ENC[AES256_GCM,data:qV9XTewb,iv:g59keVsZW45wqSihhTtyr0L5HOF+at3Ia3PK4N5bXYM=,tag:x6h8k+d6jMdiY5Nlt5GLSw==,type:str]
ansible_user: ENC[AES256_GCM,data:9RFYxEf+dQI=,iv:PbqkA6+53VLxikcpXlEAfrC60o139pFMGH/HqM4q6VY=,tag:tcTAofEufaE9FpxX46UlVw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:HFC7zEkHGyJ0tgT7UcJs7D5w,iv:xcy+l8MDac3IWLS17E2ngxSvZ37unV1NKsPyUnWeYgw=,tag:hHxRmUYDDyB7+H3dqEbtfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUitKQTFhdnA3RmpTT1VS
            bjhObWdIUHZwTU9rekFzMEhqZU9oK0VDVXhvCnFJNEtSWTJ2cFpyd2NTWHhoU2hV
            TUREZVg4c1Zwa0hTeGd1NmkyMDBmYmcKLS0tIEI3d0lVelNLanVYZTFGd2k3TDBB
            M3hDZVBDR3gvQmNxTUtLZExIYzRGNVUKW9jxl2DHvCgrx/7jy6W+6dWfWLbmiMaz
            123UbufP9aVVjq0inRmmxbnVUZR+F82xXtClSk3iFPxj2JNAc3hRGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T11:39:57Z"
    mac: ENC[AES256_GCM,data:5D4Za4ofNOrqtnGHwP/RgdomYNN+xGDYvovhA9cPgWYEWC+AaZbfkop7bihDCPn+Nu4BXlYBzMVrSTMExBP/JR5a30phW8irjaneVVqBaCmwQOFwZbtbl6Kc6wmf2ESgWEiqCHL/It7QjX7dFWLxt4J7tbQRnA17VdGWr1UM/h0=,iv:295AaJ7/IPidaCsus/CvQoJbykHqveXVbffqKqgzJLA=,tag:cz95BURJzqfW3okpT3Zlvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
