kind: ENC[AES256_GCM,data:RNIxgL9w,iv:MmUIIWuXprC3kphM+Q6FZrxBT4jQfx7LzwdQrP2tRNg=,tag:1e7w3QMGKQFMCNlrsdfRJw==,type:str]
ansible_user: ENC[AES256_GCM,data:Nx4YaGutQBg=,iv:ieWMdDaU4pyvXXudJeSIxmvG5EWPx+H466XTTD/mqpY=,tag:v162QHNS94zPHtzqPn4EGQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zsPk8N9mw6sgHBqPWV7pjZ9K,iv:Pb2RcCr73OGQH/hHJk36ybF8SPhgCc4GgDF8rfPJo1k=,tag:FMFysU3qu1b4l1nkI4ESOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ0tSZ0lDZzVXTHN2d0hH
            U1BXK21tcjBSTGdzcjJ3Y2ZiUDdLQzBOcmxVCjdZbnRLand0b3piNmZuNEtqT1Fa
            WG1vMFFSdCtJd08zYzZqcTF5cTFmOVEKLS0tIGplV2ZZWllRTEdSd1V3Q1RoT0RP
            NmNmaGoxVUZ2ckhkd1g5cGJWZkdObFEKjcF7AINsSMeEOoprUMHYVvA21ZJANORQ
            sc76B+wk8HBQxkulZTSrBAv0umXz/gQgxE9ozTj61ROIOQFEe1lTSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T11:18:38Z"
    mac: ENC[AES256_GCM,data:RhevKYy3+I461LpIJVgio9TVbyeoD1n6XXzxgeONPH9KOSwg+5HRA279LflYHPcTyG9MnvUgQIBpQdp2ctpZ1OREoTgWWit0S+vUJ7qw64LtylYhJGCEaAHLwBqwj9F/qtXHmKMLxNy1uX11oiv29TI5a/OxoiDEu8LXGr/wPYQ=,iv:UHUpTNhiafQsi6DzfLh/lvS8ZwVPZBw9/t0zG6qiGog=,tag:6h86jzcM86ql4WyaChlEsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
