kind: ENC[AES256_GCM,data:adVzenE9,iv:qiHeEVbtspbO12I7SrLCUqbqiwNci+eFI87+ASjCxLQ=,tag:VgrOL8ectiHQxuw0z1nGeg==,type:str]
ansible_user: ENC[AES256_GCM,data:EHd3pxR5IGg=,iv:ckwwZ/ZQPA2AYJ+63Oh/EuSpjt5MCiQSqfmU2UB924o=,tag:81XhdL2rfHOzbn8hi6fA8w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:NHbfStjdWgrS50CNZ/8lzrZP,iv:kAF0MYYrRaJkD25qFcglRCUu0yChKN8MhqIFQtvc/34=,tag:mfJYAQH4mltt6OBRbycAdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M096eTBLMTA0ZzZWNnRT
            YW1QVElmYllKMi83MFA3aVRTbWhjK09RandJCnhqd0V3M1FISHlmU3p0VG83Q0Z3
            U2ZJeW1kV3Z2RUVLQlVPSXMyUVlZOVEKLS0tIEZXR0VxVldQUjdlY0dsUlVsaFY3
            ZTNJM2QvNkJJeG42UmFYRmVwS0N1NVUKTy1l1p7t1Pn/O58iOIFFXfcVbrsRb/UO
            EzYIKU2gKlZuN757/0EpNdble+BwcIIr2bfhx1YUE9P2MAAeJJ5m4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T19:41:50Z"
    mac: ENC[AES256_GCM,data:leQY85DzReo7rgzyO8ByGGeTEOckh8s9a0+vgRXe4qy/VT2pHfNQFuHAjZKI/hbVcdO5RBpbkgXu/6zKkHA1KRKBu9j+HNc761HU21oZBwjDh3gfG50yhyEQFCdSqyYseiFWh35GAXWxgAc3mKHKNNZllPCzWu1Opk0MAm2Qsvo=,iv:2N3y20eqzZEHALzDXH3ZfHh7LFL9w6neVYJdy58kYNg=,tag:auz1slORC8K5E+qHQr9zww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
