kind: ENC[AES256_GCM,data:pcF7041Z,iv:yuDrgkXD7E6+HZUcA34/IZQO6jUXRfN6vUFNUA2VL5o=,tag:E6R778ipQVf6Km+mvCwvag==,type:str]
ansible_user: ENC[AES256_GCM,data:w8Ni1NXAIQo=,iv:UShcNJQlJDdThZTwc5bM1aK3l5+yFsEFg5UCMVruE4M=,tag:Mx7lPY6FUnxiA0KICVkWrw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:sfPYSySkiYaTPGEVcJY+sEuc,iv:rr+viIyiZQupuFB2GRI3KexzDyIWpXkB9Iz0QJ8707I=,tag:Ai+QvvxwytsOg91G/ICIBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxb0lsZW1oVHpRWTRwWmNt
            UHgzQjM2b29hN2FUTnlmeENydk45REVxRTFZCi9NUzh4MWlvVS9TY05HaG5mMnlz
            cExSMVR5SGQvRnN2WjFtZHg4RUtEVFUKLS0tIG92QnFTb0xobE9MejNKQ1l0NThw
            Nnk2T2xZcTVUYTUycVJ5WHNOME9WZUkKj8C+NJ7NLz7enOFzUvuAHganVmDMibMr
            dr/474Fc+cSbiBRV+AmqLDNKqz+M/30H3YCz1A24svWG5TWou8b5vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T18:46:01Z"
    mac: ENC[AES256_GCM,data:hdURygc4ULtjP3jYObB/fPrd4nT/sMXpXZ0/vQEKg7qdUd0CUuLMJTuV4XJLRn5H0JHdsk4hhLSehnGxc75TwSyeY8fi+cFOHMfo3uVHNTrooTpVKzUOZeVCFwh2wXMnAQoGEt/6bfZ/WDNyg52VbnOiTpN+vFUYZ/sVc+v1qUI=,iv:gZw1vr1msy6vsjSO7YX5sUOyKGVe3boqi/xYXGZ6wYA=,tag:OUA+fRm9nGTJDihr6W8dJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
