kind: ENC[AES256_GCM,data:STKAA5BP,iv:KmXgE7hji6wK5dQHI3jf6YgDWmaHKHcPDoIWu9tkiWg=,tag:yUv6LqybrgL/Wowbq0fAUw==,type:str]
ansible_user: ENC[AES256_GCM,data:TcRg6t5Zfxg=,iv:+79SI48ujLu7hTYs4q3+8D88PWDb4Dzt76Hxx5OFTB4=,tag:rBa1OiQkmraWTSBxH9ad+A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:SlxShGUj12BtGMIfeIAzlefg,iv:ywC9X2k3xCccDF5e5TVX48PYpPPQqwF/YTv4ur6gnlU=,tag:h+poTwzt4QvNlmFa4dnHBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSzVFNDhiNzhGeWJBNEY3
            bGNyQ2dYNGEyQmp0ZjFvL1NPUTR6ZmJuNGlnCk9EeE9mVk9wYU9CRk1vS1Q1K2Vl
            REhEQ2NWZFNvRm44dkkzM2g2QXNubEEKLS0tIEc4M0NFcnFPQjc0d0hKVmltcXJa
            OE5WZWhVNG9uVmVoYUdmYitIU0FDZncKmybnm2XitLYRPQj6Xi+OtSw/XcYlF7Ji
            u22fTuox2TWZ2T2ArGVNUrlTrBXueeXBzHQFEjpXjoOSxd5m2vidwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T19:57:45Z"
    mac: ENC[AES256_GCM,data:wgLxkrjkxK+hEcjrpDIs5eWo3uW+EO1CHMX5qQnG9K/sGFKUynVYuKRaeBI78HsTO2yaWg+Tte4sqqs+voLPQIrofigxGRtaoIwSKQwBcvAU49Fb6wtCeCWYHcGFkZAdW3A8v/xTYqIJSkpFcjKpNZHdMLeCdWA5XmCCiOfXP8A=,iv:VsTzvgho0gBQk2DhBQpMyeyFtTSA2FBLpV8eLPJzwrs=,tag:q+FQj1lKzlrUuh/1EO4y9w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
