kind: ENC[AES256_GCM,data:YQc6jsWo,iv:j701HEtkuNL+WJbABU2P5Xroujh2DPFMY/vm9qKjpa4=,tag:6mBvBbl+pQcxf+oIM0zeaQ==,type:str]
ansible_user: ENC[AES256_GCM,data:TAjDZzGB9OI=,iv:sLmzf6nJytM0hvIbc1fRevXBhyIST4oYAl7Br8b9xlU=,tag:dalTm3NILr8Earaz+9BbxQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:a1M2ttQudvYRFmpUYDMqC8eE,iv:1QHFutR79SUBDjfwYsgafGRgI0GlgYtdcoiEwEmwDjw=,tag:l94HXHQFovyKCE6gPm1eJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VDM5SVZnYXdTdTZudXhi
            cmthSjdzR3FmSFJUWFhMT1VsOEFrOXdydERBCmZCRWhJMFZpQ2JGc2VOVkxEVGw4
            RytVYThadCtmYi8wc1d6NEFEcjhCclUKLS0tIFFCY0VpQ1I4SDNMdjlja0o1bFVm
            V25mMkt0c2RuUzRodGU3WnUzZUJvdncKQsekUcKQ2JSkeaNIwzR5qT/+a4Ba0gdC
            vUIQxKSewQ5SRpsYSN4aSFnujSdf4wJSHerC1//DIA9aRW3LUAZmOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T19:41:50Z"
    mac: ENC[AES256_GCM,data:aMfjq36I3+4yQgvuTE38qoQKw/f7wFsjbfYmJRnQFp3kwTmu3kmzk1HK20YY4duvNR37AG56Lq6c/Hs5cWE06/2+fiVK7A47+yo1Bp/5ZvfuCSop3zYiasxZYfZvq6rVq3+MwYYmyQu5kZaXW/2mz2+FSfkgMmF95kMFvW7APCA=,iv:m4EaSRuiwGG1C7LGHSZsNmx++AB3MCoDk/5lH1HqSaE=,tag:OHygHD83wvXbSMPtrl9MAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
