kind: ENC[AES256_GCM,data:l8pmveSw,iv:hiJN+2mP2XWKlgbBkn/D9ap5vg7350zBvllQjIvjaDw=,tag:V1SV47WikbmAxTerFeN3lQ==,type:str]
ansible_user: ENC[AES256_GCM,data:SgSWO8Bhcwc=,iv:kYtUQII5KnkOWqwihkcfvhH3wWhmlvta1pD1wVkbVxo=,tag:+Redw8Gw7+U+7gh8QtXAig==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:VD0FKm5EXA2w6z9xWKs0/rVa,iv:eE713sqUeUcuRhY/3nVITW1kC22qwJvyIPWD0uPTbnI=,tag:HRtEdmMb28QklrEk2cE6IQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV0tHUmdia3AyZWZoaFVR
            cm5HTjM2c0t5K2FneE5uSXBWRzRRUnNsMlhvClR6cll3M1RxcmJGRi9pV3pDWk5N
            K0M0YUNJdDNxMGFkSzZEVTRySUVWZFUKLS0tIElGcDNpSFZ1TGJhdE1ueTdYblV0
            WHdkZUNWSk1vRUZmUmNjSXB6S2JuMDQKc+4dXUnvPv/fIcfV0QNKZhlLEbp5c9iJ
            t3N36oVzL/Q6UEDGLao5alAgUkDFzK6MVfWKuj6Gxdg9JfG/t3OisA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T17:19:03Z"
    mac: ENC[AES256_GCM,data:gnMH59xTsmEM6AE+aM8R5wGuvG4MqoRsDJr642ZCnJbeE7VHs0i2T9Mxfe2QHm+3OaGnWY93v2F2YfDGCMYten+obTcav/ePSG2TP42Ve28XBBJBMdNfu1zdzVHQBYrW38rRf8wZczPHoDR2Yu+erXA6KLfpNVbuKaRn80Oc1Sw=,iv:8TO1fKYwC7FL1LADGsnYIJr3vRUpV1Eh8esJ1YUzJwo=,tag:OcIRVXJCgvCFI8G1dF+pXg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
