---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      title: Apps & Lesezeichen
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: "true"
      showAppStatus: false
      showBookmarkGroups: true
      showGlobalBookmarks: true
      showAppUrls: false
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - flux-system
          - home-automation
          - media
          - monitoring
          - networking
          - office
          - security
          - storage
          - longhorn
      globalBookmarks:
        - group: Kommunikation
          bookmarks:
            - name: Discord
              url: "https://discord.com"
              info: "Kanal: Kubernetes @Home"
        - group: Webhoster
          bookmarks:
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
              icon: "mdi:cloud"
        - group: Entwicklung
          bookmarks:
            - name: Github
              url: "https://github.com/Cyberius9/Gitops"
              icon: "mdi:github"
            - name: K8s-at-Home Suche
              url: "https://nanne.dev/k8s-at-home-search"
              icon: "mdi:feature-search"
            - name: Helm Paket Manager
              url: "https://helm.sh/de"
              icon: "mdi:ship-wheel"
            - name: Artifact Hub
              url: "https://artifacthub.io"
              icon: "mdi:source-repository"
            - name: Iconify Symbole
              url: "https://icon-sets.iconify.design"
              icon: "line-md:iconify1"
            - name: MDI Symbole
              url: "https://pictogrammers.com/library/mdi"
              icon: "mdi:robot-happy"
            - name: Simple-Icons Symbole
              url: "https://simpleicons.org"
              icon: "simple-icons:simpleicons"
            - name: Kubernetes Cheat Sheet
              url: "https://kubernetes.io/docs/reference/kubectl/cheatsheet"
              icon: "mdi:kubernetes"
        - group: Unterhaltung
          bookmarks:
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
              icon: "mdi:youtube"
        - group: Lesen & News
          bookmarks:
            - name: Reddit
              url: "http://reddit.com"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/enable: "false"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
