apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2UyBxHOlT2MFWluBRuRZAiQpRbj6QWgreoeN0q4erqj+nTC1BsDdiZCXKt4=,iv:g2VpuxD3qrdY5EiUuaThVnqsWu5cKxbSHlwFXjYBpKk=,tag:oFEEKVroXJc6N4Z9+GwboA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcjAwVGhINUdlT2FjSFov
            QVYxNEJ2TWVGVFF2OHI5Uk9WQkFna0g4M3hJCjVpVVpEck0xcldsUnlSR0dvZ1VS
            akl6a0xCQlNSYnIwb09tcHBac1ZuTUEKLS0tIGw5RHVVS1YxWEZrYXRCZGhNWHMz
            NjR6cmdHMjFobzlnUUdqdGMxeVJDdDQKcUPzBO+ioxDKuckN68Mnk7naodgDLAUY
            QhhFoLx6gzC+wzill+WmgJPI79DWVBctfewGxjsD1o0rHVzdKuAngA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T17:50:35Z"
    mac: ENC[AES256_GCM,data:MU9ZanvbEHSaJHshcJPYTvy60cjY5CEpxUtphDp1kap2B5RS65M2N47gvO+0Z5y1GeyH/j/uhDOOc8uJPtCQ5d8oSuj/0lqXfHCRbPmK93a9qX7iq6dCDkx0LbPnheQPbYxGC63AkOCqL7WigaZ3oZURiU3DOp8vDgGz/HgcOjc=,iv:rLPPNL1CoaLYepShfaLzBZDVE43Wsb4+aWiTFu9uV3I=,tag:56QVX6ZYJV0OuRhEEXYlwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
