apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:n+yQYYv1YnZ6xlSZW9IotwU3EDTM15s8orBwtU+3JGEh9M2pUKsqKg==,iv:9l5MuJzaT4D4+U/Dte07dbV1rar9JWAXx6llMY2x0cU=,tag:w7APPTqQaCty48V0O4GMqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVWpiQ1FjbGVQdDM1NU1T
            RUdPNnRBbHFMT3Y3a25OOXlTSmJDNEtvSTFRCjhwYUkxMkp6QWRlaGUwbXVaM1h6
            OWVZeTY5dHVBT1RWNk9BbjlBT2RYRUUKLS0tIFViaUxsWUpvWURVWGJIZFRmNGFX
            NW8vOFhTQVZYaWtCSngzaERmbUVHZkEK2nstkmJ4tud6bVXfPtcMsOAniZeZ9PB4
            kEyJd9AEU9Fe+y7ef2cIbt4dxUCVer8ppQNBerHScQp0OWPii5F8Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T19:57:45Z"
    mac: ENC[AES256_GCM,data:qI0NKuvX9oIQncclg+XIhFu5zIc7mXzca+kIx7CkqqD8aeqftUIG4aaFSJLzjPqzIkQWDOr9N1dNMsCXn1jkkT5Z1dVipJVdOV0HTQwtv+GMVKqHpykvpPRBbXZYCxETb1tiDfu0D8PtUxcpVQHrD2WOoumDRNb2C0S5nkSdhE8=,iv:efKrLXlNbmGAsZ2Oem6TcpORvNXUnz0VeXqmBujh0I4=,tag:ziSCcRKh0b2oWPXCHhTO3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
