apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:goN+uSYjJcsUST1hzKUuhHiduFMB1cAItHIL6gfswGyboXiZ5SLtaA==,iv:cbMuHKe+gBAc4MIQnfqRIX6GOpelHLnoAwSbtXwWNT8=,tag:mJmCpL1uw2YYDCmIWycg5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSEhLQ280RWZRVVpPVkJW
            QXhURVQ3bFJBSXJweFBSK1JvOXpnSUREVEhrCkxIL2pRYU05K1VaV2h1K1A1R1VX
            eTBibmZ4SmcxZWp0eUU5TnhTYTZ6dUkKLS0tIEsxcGdqelhPT2ltMU5XNmdsbk9Y
            eDZCUDlKKzI3Y3FUdDBFb3ArWC82N3MKOeS0RQT3iHI4PeyAyUD0xLvEcqqT8Kjy
            IEMylMx841R6zA3jjh1Tsx7HgSFqkBmXwXeWW1inXb+BX3FzIlyjQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T19:05:26Z"
    mac: ENC[AES256_GCM,data:t0sKIKrv5EugEJjukcniMsf18awcRoKgdmc6cyjlfVNq/mFDxh9mAX/mIaQkwFWehVs4FMEhAYphogkMRMnxMBxonaZDkVljMCgQVFDMzMREgoYcxM4/xY+5N92NAg5Ii/Lx9AIkDtJZMEGMF3QWPHuL6+/RdevkBSA/Ab12ic4=,iv:TowqD04z9ZCLLhqx1LA+lNEAEay+fDo9CEgEAcitZew=,tag:WlQHB+/QpQoNV7qLNgmChA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
