apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TbFay27vcnUokO03A7MAfWdFJgIHDn74yBu0yZKkTDFPYKpSp4hyCQ==,iv:zBgABsMvy5h3DQQxJbBV59Ew3C+XhJn+lEVcloeJfXc=,tag:tCMnogcNvhRCARvebXteXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbmdJbm1vVXZLV3dxRDhK
            UEJxRk9BckZBMDFxK09mZzl5T0p3MnFDelIwCmhxd0xSMkkvR3I0cFd1OENNTnkz
            eDg1QjltRGJwYmdIVmlUVFdvanM0STQKLS0tIHp3RUVIZXg4bkR0ZUNGZGdUZzhi
            K1RMUWVBelhvaXFrdC9ZUFRMbDN3bncKtffc+D8OPMIStQ/kgQBoH7buyqN9ngNm
            OjNa+2dK6D9cVtDg3JZOpuQTC9ycCaUTEorLbXL9y6ZO0LAlMujUgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T18:36:25Z"
    mac: ENC[AES256_GCM,data:3Aq1SMceTaIoqw1oXfnURavJxRW36ELFRrEDSTytiFKOLgBWs4LDd1doNRXVRKPhVaOUBfn4utNvO6AGUJcCAnnfDwSXLyRvvTc5nb0UKmtZ9RxBe8n4oCKjOJy9ebQskFdV1Mp0gf9GJ64iVH3SXuL7kGbhoD266sdRSsxsO9U=,iv:rMXks8b3P6beJOlFCV0QySlYfBYy1VFeNdlej2PeMBs=,tag:JFxoE8mpJKsTlwKTQicqnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
