---
kubernetes:
  children:
    master:
      hosts:
        K3s-Master1:
          ansible_host: 192.168.5.10
        K3s-Master2:
          ansible_host: 192.168.5.11
        K3s-Master3:
          ansible_host: 192.168.5.12
    worker:
      hosts:
        K3s-Worker1:
          ansible_host: 192.168.5.20
        K3s-Worker2:
          ansible_host: 192.168.5.21
        K3s-Worker3:
          ansible_host: 192.168.5.22
