---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: confluence
  namespace: home
  annotations:
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "confluence.${SECRET_DOMAIN}"
      secretName: confluence-tls
  rules:
    - host: "confluence.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: confluence
              servicePort: 80
