---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: confluence
  namespace: home
  annotations:
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
spec:
  rules:
    - host: "confluence.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: confluence
              servicePort: 80
