---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: office
spec:
  interval: 15m
  chart:
    spec:
      chart: bookstack
      version: 0.12.2
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
  maxHistory: 3
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/linuxserver/bookstack
      pullPolicy: IfNotPresent
      tag: "version-v23.06.2"
    env:
      APP_TIMEZONE: ${TIMEZONE}
      APP_ENV: production
      APP_URL: https://bookstack.${SECRET_DOMAIN}/
      APP_LANG: de
      APP_VIEWS_BOOKS: list
      APP_VIEWS_BOOKSHELVES: grid
      APP_VIEWS_BOOKSHELF: grid
      APP_DEFAULT_DARK_MODE: true
      AVATAR_URL: ${SECRET_AVATAR_URL}
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: bookstack
      DB_USERNAME: bookstack
      DB_PASSWORD: ${SECRET_BOOKSTACK_DB_PASSWORD}
      MAIL_FROM_NAME: "BookStack"
      MAIL_FROM: ${SECRET_SMTP_USER}
      MAIL_HOST: ${SECRET_SMTP_HOST}
      MAIL_PORT: 587
      MAIL_USERNAME: ${SECRET_SMTP_USER}
      MAIL_PASSWORD: ${SECRET_SMTP_PASSWORD}
      MAIL_ENCRYPTION: SSL
      STORAGE_TYPE: local
      STORAGE_IMAGE_TYPE: local
      STORAGE_ATTACHMENT_TYPE: local
      STORAGE_URL: false
      AUTH_METHOD: standard
      DISABLE_EXTERNAL_SERVICES: false
      DRAWIO: true
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: bookstack-config
    mariadb:
      enabled: true
      image:
        repository: bitnami/mariadb
        tag: "11.5.6"
      architecture: standalone
      auth:
        database: bookstack
        username: bookstack
        password: ${SECRET_BOOKSTACK_DB_PASSWORD}
        rootPassword: ${SECRET_BOOKSTACK_DB_ROOT_PASSWORD}
        replicationUser: replication
        replicationPassword: ${SECRET_BOOKSTACK_DB_ROOT_PASSWORD}
      primary:
        hostAliases:
          - ip: "127.0.0.1"
            hostnames:
              - "mysql"
        persistence:
          enabled: true
          existingClaim: bookstack-db
    ingress:
      main:
        enabled: true
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "book-open-variant"
          hajimari.io/appName: "bookstack"
          kubernetes.io/ingress.class: traefik
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-external-authelia-auth@kubernetescrd"
        hosts:
          - host: "bookstack.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "bookstack.${SECRET_DOMAIN}"
            secretName: "bookstack.${SECRET_DOMAIN}-tls"
