apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:E1/uh9+1oLMUyLlsYS/mxo+I0yOW+MaVNkDbYIdF7VRQTw5vsw==,iv:73QkySsJxriNh4aWOXbOmN613T3CsH3gdYk7TFyv5l4=,tag:8TIQJv3AG8bQnQJ7CcFQSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV0EzamtoSGg5VXlMNWVs
            V1BuMFFTRjkvd1NRVXNKM0d0Wnp2WUtydjM4CndlbGJ3c00zNDZRTFJqZEJjbHJz
            ZU1NQ3RCNDc5elh3Rm5xRDhpeTBZUm8KLS0tIFVjdGR5SDJaS3FZZjFGUk1mMElH
            TjB3cjNNaFUzU3FzM1UwbXhFcSt3VnMK1q1tILCVHvz9/z/07UJd5E5hBT1ajhfy
            U/BmwwmybQQwpJ0MJWqvdrWQ44KGFBRlZqqBOa/5DhXjiV+KkrmIEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T14:50:36Z"
    mac: ENC[AES256_GCM,data:EKX2pOb1hsJh4QjTJuWQMF40MWFl8puO/HkpkNxMSyGSxGyr8WWVAbMtjfi2gqS+7JTaiIf3soGDrNALlXjAXXfP1DsOevdV7f8HhWBxUkq+Zoldm+a0wq1fnNqKXmtfF10JC2jEpGclIlqfU+JhwcwXt2ROLrHmdTjnQwMa1w4=,iv:AR98/wWd+GQyjoajrEDEqT3VpQSod8Woof3s3Mp8R70=,tag:qWUpyduf4rvfroH0BCQAlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
