apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:JJMmYfiaxbpk5n0A0TbCzF6sBe1P21VvaYR1xnq/7UI809jgiA==,iv:pRiFX/ph4nrjajyYdxLrmtJX1Bf4kQ/IPW8iQEWPnjQ=,tag:sxw7M48YtFgJ3Hfwdo0vFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTkYrb09hSnpuZVh6R0ZY
            cUxrZzhxUEpaZGp5Q2lBc1RUSGptNURyTXpzCmhNaWNrT2NGUkRsTnZoUG9hMkN1
            QWJwNTdmTUMyTDE0TFlJTG1OSXFIdzQKLS0tIDZpSVNBQXRFUWZwdXFNWnAyU2tm
            QVhtVWF6Q2QyUGRiNFFRbDgyQWEzQlkKMphK2j0yxkIvauqpeV2hU3BybAXPYgfR
            sm6DvyB8Bw7e4J6LjXf5GTPtp831aQ/utRt3UFS3b8QgwS+oKb7+AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T16:01:02Z"
    mac: ENC[AES256_GCM,data:724slhCJATEIh9nE5jtBn0ywHogXpT6+yHenQ3DXYc04QlbT87/msnvVVK430rnLx6efpfSIz07f0EM/GXjCAQObK/mRUJ+nXOEmsFZkI+Fv3rCDCBndWkWFSP0iFaIytmpjb0hYYUkfFQbP8KvH+26MhdnyqvAhzbiVBgEMPY4=,iv:1ZxupJNy4stt9SvaT01Eyvxr6obbQakDFLsY3icFe7o=,tag:T50q5tmxKIG72hUjS2+80A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
