apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:5AvhNWGB+wFSvmQ+i86RXmBzRD/RNZaHTnfSsCmKST9I7pgKtQ==,iv:fO+4crrEqHeR2Fuy58clmdoUGO3YUZ/Jdr69ZdX2EqI=,tag:IlDtlv2pwX0S2+Qe0Z5WWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNnhTbW1MVUpnSHdpaC90
            M2NrcDhZY0ZteFpnM2NlbXZ1Nno0K0FDYXcwCmtjMzQxUWEyL0Y5elFqL09wY3B1
            VHdIckFaQ1d5WlZmMnNpZGN4L2loSk0KLS0tIDZXeUQ1QzIzWVloWENYdnRZbnJ0
            c1IvcGI5Z0UxVGF5MDRUTVZEWTEzQlkKAL8MxuaTtegcr36249n5J78i6UzQlK3Y
            R7IzxK68lK/RItsMoGWUymXautzNiMEGIz7LXVj75UkWDQPeCwuTNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T16:46:06Z"
    mac: ENC[AES256_GCM,data:87eU1QI0U3wY+EtC4w8HGkJzWKDQ5zH4Dn+bD0F62oUbz4BeI/kJKjUWSmvUWLTn+CPGKcm1/pmYDshxt2UwibjVN8tZ7Tw3YFVKtjBJO0uk2/npo+DAu7hvDoXnxw6wq4flUJWXdNbNAiZtgiZvM0YwWoJOAItTkGn3HH7akvU=,iv:v5/REoCu4LlKJjlpuQZSQgQTXHSV97jCn4f2cDUXipg=,tag:30AdhlzAh78/VfFAWCVFQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
