apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Y5imlOZMbxOq/BCfFZRxa68EW+pwlhSL0SXjoPTflzKidaKCmA==,iv:cAq0Zy7pmBFVVs+FVcxPn/vEYS9l6NJUYGvd0/QI9K8=,tag:5IaJd+inCCv+OrRqAM7Fvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OFhMcVFtVWdEanZiM0RZ
            OUFCZnAyUlowNmNVQVpXZVh6eTlMc243dEZvCk1xZWlKaXR5WHQ1dnhsQ3YzR21l
            ZVpWRXZRNWlRV3FKTGFmTjBFazdIWVUKLS0tIG1rck14RzQzSm44WGpBL1JLazlE
            KzJnSmtWNWQyR1YreVBSVTZBUWZUY28KM/CHfYqxzhGAhQO9KFHxq8o/tJYYwcyS
            1GokNES72FVq7Ktpof6gQKj5F3L/ByZ+TIqqwB0bLkrXdDvHGQJ4kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T18:20:56Z"
    mac: ENC[AES256_GCM,data:kgZdOenp3gpYZpFgBOQ2kZ2jpQ7vjDoloIuiMVgaQrdsbJD/8OoFjyuhzWYrL/7zo4j/AkBf5Zqr0OoTO9sTz5FDShq86vafFXq8b7Yf9G5nKdxjUWw1yTMKKub2G8Hg7C/XX0a7N/U+ja9mCvhx4NDGxzOEEi349etlDRoEfBA=,iv:3KZc1NGSKLAw6nSEBklZgPWtWlK78Y3WgbCHb83Fjlw=,tag:8ff9j97F3Z4RstT5SgLE+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
