apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:0Xi6wlmRbWIToc1HEFB26TCNhFspeZ1mREjOd9lBaxK54G2V3Q==,iv:TD99KFZduIJANKb0wRcaR7zdYdQV5ukFoo0yWcbZvxk=,tag:7YQ2UNiJ52dRMCkI/Tludw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMalpMQXVRb2dCVGhBSFp0
            QkRuUkRLcFFpbFFLUEUrdUs0S0FzRndPSVNVCnhpMjdMdnVNaVFJYXM3SWxaNEFp
            ZGJUQVZmL0k5Tjh0UGxPMkcveGdDbHMKLS0tIDdVUTJKcjdaRGFMRjFzQWhUR0sx
            Y0VwRjFYUHlNRlBpZE9yZHJIVkYwbDAKnk1Lc0+TSjMDSZGY1q2ZX7ypU/tTd1xb
            RQ25erHMmk4Ct1CP+Z+zacV/tY8BZ9iMWFpKfLDqdF4DleL3RP0Txw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T18:46:01Z"
    mac: ENC[AES256_GCM,data:LrT4zrHsOU9g0ncsrpGq83r/0gte+FPOClT2GqPfWaancp09mBkQUobDXgFm+DfCdoem7cl0GY6kC0/iJZGpLdvbIqQ3Efz187bdSja3ZBt6mA2Yj557dCrttgGReKW/2s7gg7Pka2sYL2O4c41dT3k+avpQYbBoULVSVygbop4=,iv:fPM8oREKOCyUA6hGUaEjV+T1Q0mTyfuIxMVwW+oMYZY=,tag:3ErUUP4lX9YLPMPwmD2JRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
