apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ZOiH0/DHxqSe8dA0cMKu85mrxufFk/GM7U3HB7moYHo+f+R2LA==,iv:itK74oVusqG6irUSVj969D4ql5+s9Lq1/1tkqGlMMgg=,tag:LmfpvK7nIEXxi2RGrJ1jxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTUhuUWRFYUJkWnd0WGp2
            eUpNMHFTOUZCa3FaRXAyZmpiRnZ3TGpjR3dVCmthZGtucUQ4dFBISjlJTE50bWVI
            a3NoZjFXTE5CMXlWRHpGd3RNTW5KNjgKLS0tIFBkQzB0djZld1FUZ3VDWXhIUFZ1
            RGVpaUN1RU1objQxUi8xMXVWbkVvclEKlhzyXZFb2CDqei1mnacnm0VPkULUtbkd
            lkANPkPb5c6M8R7LR+PDrjOmwIV2k6JXCmzoOSc3pwsXaocEqMkv6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T21:11:56Z"
    mac: ENC[AES256_GCM,data:y7Fv+RQp65bm8v1pmD59p1OmWNAaHDicHafqIOXdCXZ38yFzjMBaL2idYCexpQBHk9pTYfZA7lBnMaCfV8w196ZmC/XfyDz0LQqcbzw7Gt/HycLGylgq+HTFfduPJQSoDyv6IraF+D1ElEbz54tNGWRywK4FXWOe66E6v10W/CU=,iv:0qN/2DTqzAaKIbcx6UP3/xoilV/j95Wnc8zI8gYSgx0=,tag:LQn7VUgYdi7fARuxef3m1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
