apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:XWZLDYwAfy7L7zexinnYvzYuCFDNVNIytAwSgwEHcl64Ow3xow==,iv:ZBETcZf+NGAXSuvT/7XC/HBA5rhnJQHJQ/u8xHOui2I=,tag:/BOucIxkICZA4OS+QWYZ3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOE1waTFHMC9CQTBVaUts
            aU5tNjJxZy93c28zV1krazVaRllSaG96a2tjCmZlRlhxckZxOGVMdUY2dURuMElq
            YllOSEVOVmcwV0tobGtiblFmUnBpM0UKLS0tIFgxaFZ4VHl1b0V3cG1tM3VsRkU0
            UldXRlFGbXlNTlZ2bUhrYkhENC8rbW8K2YVifNCTbBsjWUMz1qcEV7KlTyTZuama
            XG0uzuqYJ5fPLCepHf8ZA9H2p0lc5YHHEka7GVliIX2Xid0xxpYg8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T19:05:28Z"
    mac: ENC[AES256_GCM,data:HyrAQuzd4cZZdU8YXaHzsOxKBZlm/oFfZUXMr5Vlc9RvWyYzXdfuemzdLorXxhvBS++lvF+X5eGVffCQuKMM2V5FxCx7u2/3C9et2VV8SVa9OE1zGKj/k7v5ZZAA3eFZx7XVluEUB9rCwqt5kq+R7Cak4jWQDEwSfD1TQLgG0jk=,iv:bykt3amXKdnYXJC/A/zBTniSCzp0JBnGOFMJJdo2MkA=,tag:In0yI+vUKpJkLeuyNwA/Lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
