apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Kk4PW+IEAQVN2vS5R3ktSec=,iv:9rQ2B5Fk1Fnix5IUbaB/nxpFtLl+pY7qBxn+e6kS7oE=,tag:ZH83hPQVAVZtCat4lRuWcA==,type:str]
    api-key: ENC[AES256_GCM,data:xCoEP1cqo3iZVV0ZkNC+UbxwgjbFagjZtIZ7oBkBDE76DpwPKw==,iv:zlfGCUK5l3b20T/8N5x7WzxjbxbejUQDVSA5gnBkX/Q=,tag:/a0Vo2ER0cphB7vjxcHfGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHd1Q3dDM3TjdjdUx4L1oz
            bm1FbDZzdXB4VlF1dWFIaDJQRWRmenRGdW44Cis2aVpiallPbGdOK0NHbnZMSk9v
            WkgzemMzV1pFL1p1VTFzL3M5dzNERDQKLS0tIDNNQkVKUXB0UjViWVc0NVFhd3c2
            NllmOFR1THNpNlpMSTRrUjdSWk5oNk0K4O0u3xmytQPEl5TLIE1oztmmoREmHSH2
            fGKcmCBfYvMPVDis499VF99NbtyG9a3lNYIZhfpCEQ6YMbm7zffJ9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T16:01:02Z"
    mac: ENC[AES256_GCM,data:J/TSYfM6WVk/gJqXTidYpZqMmX99DZ9+8pIvX12cR1IQ7q0FlGSMjKk0t0wox/WV6YRe+jtWLlI8hAZ2+cqtn1gq+HvGRbQngXADwTjDgXvjI3jTwO3j50NPilpovMpP6FFCyz4u7hJWm8+rv7xoCGWwR7k/zOJQPpAsapinP+8=,iv:pgEWLT3koAxfJF7Q5WvvFfDwvamT1Y7HKo2+NaUuM+c=,tag:Qn5DFKWKRX2X2xJrclwBPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
