apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:vWOhy3/IjE6fUnLOgNBCPr0=,iv:AlaI8m7Mo45WaSwPymBX0TL1mAm6MruqUt789ys0Rc4=,tag:pktaEnZ0CODQmhbmAJ2vnA==,type:str]
    api-key: ENC[AES256_GCM,data:IU+OYiome1AGqrYkBF+iD3Owr8PLa8j0i9NtLw6GWKowwXdbCw==,iv:eC2J6vcIZqS2b4kjdqAOEY3Sg8n6rTXL3c7dLN04d88=,tag:J0JpHvAb952IQapP5VQ22g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeklBOE1xdnkrWUxDS2NX
            Mnl1RG03TEFUbWxpaHR3dzBxNkc4c2Jyd2lNCm9lVmtDU01ZdG1xaGVnQUR1Ynl1
            Ymx5SlZLZWpjWElyT3NROFVvQnYyTGsKLS0tIHRUOFJ0T1VJWkJMd0cwdXE1cklv
            cWpzaVR3MWNPd0NBN1hVY2xXMjVwRUkKf5JgnuXFeX6wrZrj12Q8h9H6EarNL7i2
            wABSwLx7nvqlpx/o8r8T9ho3AzNxpTRS4ca0QTwvplUNPy2ReAPPlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T17:54:48Z"
    mac: ENC[AES256_GCM,data:HuWpG9r0oPL7ktogUte5g7TXQPC01OIiAheWt9JfS45cwpCxMiZ/g4tKAyE1JppnEifNpTPtM3qlGNF+JDTyzNpX/fNSWkWGKbw3TCPyDDXoqixc1VFoEQfMHSzz0EzHtjoRdZp91oxWRroecE5Mb3MIgdK4v5t94xSXLEUyE/w=,iv:Fxm1FK5cu0uA5P637GPCcNTKRI0inUyvCfthlCXsq6g=,tag:igd0tvznfIjLrAUji3v3+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
