apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:TSh9/nU4ErxbpQzEVn56OY0=,iv:/yP729ja2vCSyiDdivJ28MeztMMn36/6AA3E3z9g4l8=,tag:WuonUO2X5+b1tbDtoAz98g==,type:str]
    api-key: ENC[AES256_GCM,data:Yl+JO/nIAvHNENvRsN6HfG7db//pLZzrl1v4BdTlWVBnMP14lA==,iv:kptksEtfEkBYhdU0uzTT4btUw+hn1Vkl6ew3i7JD590=,tag:/xqGRrIYZXN3ZOHS8PAfGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWWJ0M1VRcGRaeFFsbnBa
            NEhGNjFlVm5PY3ZiTDBOWUh6aUsyZE5tRmxZCmd6YWN0cnNJQmY4V0dkbkR4SmM1
            dm5EeDlRT1lzT2pSWk9BQTlIOXhYRWMKLS0tIFFESTN4YzNsVWNycVE4RE5VRzlG
            WEUyYVQxWjN4RE5Qb2gyWkdkckF2THcKWUPBZx934SNHvbJDLG6mqWbg4RKhCtZV
            yDmEB/BvsqvmLprwNXUt7adruStWfltdPquk+FezPeWl0hEcvVpJ6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T18:20:56Z"
    mac: ENC[AES256_GCM,data:ZbLXyZAQJpdx9cFCEar0OkZDz27CwUhxwM9w/OcP2Nc6oJvsAxBo/tPKmYB4CWhKalOnxytxGIdy2yYtVRLBjbyZJU0QhDWo52FVMdqmRNWu56WTOavPj3KASxSsG6NOk2X7ig0fGC3ENAG9XIdlVtgyIbs5I/W60QXrE1/pIFI=,iv:3qFeEHkBIILZsUm/tPGOIaHYhaFccoIG1xS7k35GPks=,tag:MbbFHlsx9ZhUSQLflHe4Lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
