apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:QpoRT1kEpwqetHVRxGkKFEQ=,iv:wdA4VjTI9e6ameXqSKX8eKynwwP94Nd5lzTjdtwivQg=,tag:vfmqZlbbONrynvUmExeiig==,type:str]
    api-key: ENC[AES256_GCM,data:p1mogpOO86O4aBDuPbVLo15kIIPc5Y5OM04ia4R4UvkHU7kDbw==,iv:OAynMghaRqip2SDyXndcImnuAMYaAIIYNfQH3LrfGQI=,tag:q+2QfoTNV94phMdQGMLk4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZEhlK2V5NE5nSnBLaUZ1
            dncvd1RiZks5REhtdE02MCtOQkNmZFR3MFNzCldGMFM0WHFVNGpvd1QvdCtyVFlk
            NkY5S05ySS9ibUpicnRsYlNQOUFWN3MKLS0tIGV3VjVRS09lb0pnTjRHZnZMOHQ3
            T1dyWmloTmViSVR3WTR5RHVsbG91TXcK0ntqF3XCoQ5V/OKJ6TwFW8Hr0kOiJEOM
            NXeKtldSSofH2gvMMrgok9bl0Ry8zDqKZPBqJZ1KNFuHkC2iFvExhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T17:19:03Z"
    mac: ENC[AES256_GCM,data:SuWyLVFSHerhArnHS+/zFEqMber68t2NUnB8ESKWoiOpoD337ETuyHEUmC94JOPBAISDlv7oEfh9tFr6zzbsOK/iKL55Wu7H5qB5hKZS5JOWU6PkI3eSJQVF1pgAtkHI2CWXaGocUB7tBOAA3mHBagKQVOHwEUPISYCX5i658Qo=,iv:1vpiWeuDYMgqQ9pmMwSNDm379h/vh/sixPZFM0aZQoY=,tag:hlxH6tEFgec8aM8COTmlHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
