---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    image:
      repository: traefik/whoami
      pullPolicy: IfNotPresent
      tag: v1.10.1
    service:
      main:
        ports:
          http:
            enabled: true
            port: 80
    ingress:
      main:
        enabled: true
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:id-card-outline
          hajimari.io/appName: "Who Am I?"
          kubernetes.io/ingress.class: traefik
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-external-authelia-auth@kubernetescrd"
        hosts:
          - host: "whoami.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "whoami.${SECRET_DOMAIN}"
            secretName: "whoami.${SECRET_DOMAIN}-tls"
    resources:
      requests:
        cpu: 15m
        memory: 50M
      limits:
        memory: 100M
