---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 12.2.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    auth:
      existingSecret: mariadb
      database: ""
      username: ""
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb
      resources:
        requests:
          cpu: 15m
          memory: 184M
        limits:
          memory: 184M
