---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-xfs
  resources:
    requests:
      storage: 10Gi
