---
apiVersion: v1
kind: Endpoints
metadata:
  name: bitbucket
  namespace: networking
subsets:
  - addresses:
      - ip: 192.168.1.110
    ports:
      - name: bitbucket-app
        port: 7990
        protocol: TCP
