---
apiVersion: v1
kind: Service
metadata:
  name: bitbucket
  namespace: networking
spec:
  ports:
    - name: bitbucket-app
      port: 80
      protocol: TCP
      targetPort: 7990
  type: ClusterIP
