apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:kxZpsZJK4RbYivSP0pl0wdhRlWhe3/WGzd/bJ6RBRL+20o0QzuDJc04u5OMJ26xIerP0cJEa73M3w6ce,iv:g9ISqJlI9ZOdam0BTbSDb+KY+2ZHvlPiASBjvh0GJ/4=,tag:qpG1ENglTx5rUj/6Wd+FvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTGRzOGgwY3ZwL0xhdlBK
            RW5xWnVEeHNzTi9abmQ0anlRQzFXMW9wZzMwCml0QVYwWDc1aUhzekxJOXhUQmhq
            VFFrNG9mQWxvc2dNd0hnOXIzZkxjQW8KLS0tIGMvY0NRVHFleWwyWml5OVR4anla
            ZlpxS2NUK3dmOTRINXBVUGxzdG1HRHcKSyieTNwzDGpz/I0IqreFVFdtZIFqLe9e
            cP2lnFzoxKaO+injpmcEMcz63bK6+NUsOp+UMDojoV4Bxle1PqpIYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T17:05:59Z"
    mac: ENC[AES256_GCM,data:hKJxsJ81B1I/gDmfNF21qil++Xht5dFEaAWToKnqnsqnjlqRp+/bM8uHdG+F2VwZCHXkYkIEvbZwB/O2BQkLfkNtVp5bmG03gFzEQNes5DKMdiFoICwzFgbk/4Fn9KPhOPcuL6dm1UHO1DGHhjcoJ+CZhSETSyHV5OLlYkGRPPs=,iv:vOnjS9IY2pO2+f4rf60seMsC/Hw+vTOsaV5HPF82akM=,tag:gIrUMJc81vr3Z6ncH2DInw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
