apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:nfrOmrlHQQLLNuZO/J2vBjAC5wUs6IHDbUon+vXvhpaEuOXKGsZQ9ndXtZG2lTF6wJ6efk7Pxp7+0UKe,iv:fA/aKqVPSZwrtm5CNDoOmovdjL5Sf2dugbWYlH6NDlg=,tag:rWggVc5CfjcXygGO1KEM2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdWxLNWRUNURkZkJvRGxx
            dGFtdy96NTV5Q0pYVHZHcDZyN3dWTnpWeWtBCnlmbUNlT09Ub3lXNW9wZWRFTWRn
            Y2pkbGxreXFxeVd4QnA5WmJkWitMY0UKLS0tIEhtYS8wRVNjMVhjYUEzazNQeVRi
            ckhxczRjeUFJR04vNVIrRU1xRFJXazQKk1fBab31aDJoaKqn5wBlYYwOPMmcmyRz
            LtON+/gtSMfhTa0zijaOhog1KTOvSP+C3soTr35qf/k5Rk0T7K2Rmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T17:50:35Z"
    mac: ENC[AES256_GCM,data:453/FaXHtn8FC3cTFLB2v8I74r1WApUj882alALiKqj3eNljN888SQfJ1w2PtVP1akU15uKXHSaquLCI6YNBy6fNPJOiFzWOpgUPkVACfjbVntdmzsInfaB53BZ9+8Lgo6rJbSsXQgS4yRmTb0cRV8T8h74FZCD/PWDyox9d4+g=,iv:ZuuDNlxQUzSFjfE3rquTDx3pQLg0R6GXvFvHAH6O4Mk=,tag:bROClPuff931NXFTbev9Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
