apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:dq0d/h9+yfFIygahHybRsu2+zVxKkPBTpvJu1NBmwX+xcBv/MFbtC4LCIQ2qIuZ7LmzpFf2/gFKxjUp7,iv:89hDkV7JH3+6kLyv8fH9NaaQSKG/816mxTPv24vJTqw=,tag:4agkgOrj/xFYfms+AWVPHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSjl1K1FBcnBrbjN2MGhT
            b3ZWbEpvOXdiMFNxckN5MFYxVC9aQjN4UUZjCmJRMlNHL3NYZHgvUDdER0krZnRH
            b01jRUpocGNHNEJVRUZYeVNsS1phNmMKLS0tIG5VajQxWkZDMFRielRwa29kWVAv
            ckxoQ09ZVldwVmZnbW5HaUo5YnUxNUUKZs/SXaaCe1GjrRH+MVhJ+ZSJ0htPKk+x
            D3HFvARbIsOIuwsSCn4sJHHCMRjjl6KH6tKXmhGMmq3jbFGiiPOOjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T19:05:26Z"
    mac: ENC[AES256_GCM,data:RPm1++tMS8V+VHYRuF3KRiNoJ8hdE2xBOBSjlnUUWoSe5cmdcmyv9X9rwwHP7LzKgr6mkysegavI6ewrvvhJ8CLaOHwSqDDBVi9kJc0MmupHxUXcIdhCvk2UmXZYzJcCsRUHC5jyYWAyh1UZthiznE4DAadM6SMtjytRpLua7gs=,iv:yWVQdTQxsqwXg/MX5czNxYlWdq5Ypj8cGu+Stg4yIKg=,tag:3nQA/qOC6FsTYX02chBnbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
