apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:/nvqzNW6iQBHxnFaO7rnaOvNuNG9d83JomGszbEsCUM6xUjlfW1kkfqxBXrXM4l9qkR48jdIZQ1kFbij,iv:1cXacBBC7SqdMmLnXAPevz8YjjfF9NMzjZjfmo+eo/U=,tag:9fh4D70viqBdqMSJlODDgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L3VoTVE1TVlPNUVrVXRt
            azlJNG5uRFB6T2kvUjB2TmpVZEdUSVYwWkFVCm9xdDU2cWFOYjllUnlqTUVzVFZs
            UDFFUklBMjBWdTFMS0lRcE50VXZEcTAKLS0tIDFkQUhYUXdSdjFRQm16ZTJ2cU9t
            ZHlKdE5QT29TV1NiTC9menpPOUwyMXMK5sXWLBJpcvO/5UUT8DN7rSXITSO8bEBu
            ILs3OhzyRYVxXNRLfCpWmz0qj3mLOHlTMGz6Igy4CtdcXQ5Ac4UvzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T20:38:10Z"
    mac: ENC[AES256_GCM,data:G020Dw0Xi+4WStZ36A2sWSuLzCgQRYEO0Or8X5Uk8FnbEDRS649ABrIFDP+RuTkSQyq+12GcGtRjDG1p/8f8W5gHDGrN9wGRU/seQnHp4sf5Pqws4PMZjff779pKlQ2CcW/ocKHAQBAvASsxXQN0ZwLOZBPOpmcBBcZvhO0yitE=,iv:LrGtcOv1fFshD05STWzHQByrIYWBLu+dJ6263Pd625c=,tag:TwM18F5XW5xHfuKgqNrO6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
