apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:z7aDM5K51owdhEkSFSDQenCXlKDEb3znnJnzEnf59LSCg04biU67+mvq+KaDl0FSBD+i7yxyPdfUwqfb,iv:xRhu4XoKHFRItehFFY/WakVakxbupOuBUtNOere/nG8=,tag:bcq8vO76gXpvTg0ubUXO/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQktYclpMbFc4bTNrY1dJ
            Wk5xNUZ1TURsd2J2cVpxcWlxOU9jRFZiNDM4CkFXdVk1QlhTTnRuVWYyQU9HRGs2
            QlQraERPZkRNY3BPeHp1RXBxT2NvRkkKLS0tIGo2RGVuMDNoNWVvMERFZ1ozeVl4
            cmtBSC9KQU5pYXZlTlgrWXVZK3p5Z3cK9QHejSSRn3fw4xjjz3Wt6X1QV5DR9y2S
            nbWW5abBrTEbV2f4GN8G58q7v5YTIGH525jnCa5e/4jjMCyoMk/MFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T11:18:38Z"
    mac: ENC[AES256_GCM,data:ujWie0X6iE5MfHMFyFqP8Mah/OmmHuesy6iq+aotDkFe16yo3kiOEgFmiVBpfbKbRhy+ptie/jFS4oNjaZBcFdJ35xbG86T5/d+X98QAiy6Pj4LcrSQ2Yiw/e1nNirk3RijkhhbeKah+NJe6RWtVexQi+Yfmmmh3NTT03xFXmJc=,iv:2WzQ7KkuvWLRLwDnINk2qpblB/wSBr5JIfHXZXRO1Dw=,tag:ix0wX8e8S4ZuGUCni+QYIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
