apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:JAQJa80NCXvFFqJcZne3ZfZLODpNHMRTIGJghc7gCTHVmXNA4oDE2akvnWK4aLK+pDMY2ebOqtf/UTit,iv:k5nbjFHgvQzn8wMGMV+4NuQMSHzNOkh2S3ElHbzJMz0=,tag:bbRjTktHMEoN/IMUwSMjkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MDJFbEJGTnpzK0dFeTF2
            OUZKMml0SU1HWHczS1NyRlhjV2dkMUZGcVZRCkVTTGRmdHNua1NpWjNSQkxJcnJ1
            ZUhsOWRaaG1zanZDNDJnbzRMYmJRc2MKLS0tIDFxN0VWc1I3ZTJQd0tJbDVaZEVR
            bGxjWUQ5ZWxkeXR5L3Rsb2d1QmZsTkkKqPAGWxwo0h833qGzLbL3wSrRupWblyt3
            m3ixpZ/4DNwENo+45Y8l5oiQs7NyXm5rtnsuLGKcnJ1icyk2HFKUQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T19:41:51Z"
    mac: ENC[AES256_GCM,data:GYQ+JM7FUatFV86PJq1i/MGuu+1c7QOBIEjXEWir2wC69m3iTfw4FPDR1E6FX4JvdYveylUaQscvJL8kdnWF4bVzC/lXMMJBk+ZusoEspAaev7sRLAzxZ63uX/fO9U2FQHS8s20yn/4lXcbcMp8IsB6+o4NHs/g78W7CI0sYh5o=,iv:Y14SzwUSh8qBxt1sA/peceuyxZEyDI2Lp7DHHxSpd6c=,tag:VaLRM4LtJ5BwFNpZQXoAiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
