apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:CK+6lAhKX23CRL8DV+02HaxExpoD51k0Y6HyS6EzXFTnHl6ary4muUYFZQpaDQLR0Iz9HGGqgfYTDRuX,iv:6Y5Z4xgkHu1SQl/2di828DSjWuPvMIJiLjWWIigAeV0=,tag:un6X1ugHOJb8tpjrzT+RfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UTU3S0RaM0YxeDY2VmR2
            T05CN1pPak82ZjhNUXpIc0V4Uk9TOXFZVmcwCnU5ZHBGZFdqdVM1WXdKTXNuWklR
            OUxjNU5FQWlSTTk3ZHNGa1kxVktrS2cKLS0tIGpuQUZtY3YzcDhBSndRVFIwRFR1
            L3JVVXk2ektLZTN5YnMvcnFrWmh1VzQKHkxSjksCTC0b8UU7beTDNQeLLc9GpfoM
            zcuIZTkOitJpjeiFnh0buINCjpxM/XTKK6n9pzdCffhuT9vp2T3x0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T17:19:03Z"
    mac: ENC[AES256_GCM,data:YNCVDKz9rGXH7BVXoM8sZwJEk3wjDrhLFvVFvjdbnfZ0ABb+PnKy1Lyxq/vvz9iihEaTwp7yGAtxlZbZ4q2c3QMViOdT0ezDWHX0rj3GbLt6vjoaOJ/Tk6RESMq+SAKuuky+PxkAqz66Uezg9nWcN0m9NFAAgqGQDt3qkWbPIQ8=,iv:UpPTyra8sO5a6rasvYhvIgvUHW7gyx2yDJjuDjlRRnc=,tag:g/a/Wdjmju3zUPuXFU4kqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
