---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-app
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/longhorn/app
  targetNamespace: longhorn
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn
      namespace: longhorn
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-configs
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/longhorn/configs
  targetNamespace: longhorn
  interval: 10m
  prune: true
  dependsOn:
    - name: longhorn-app
  sourceRef:
    kind: GitRepository
    name: flux-system
