apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LMxLFWsKmNOK3dA=,iv:vdNs7JNx5ihG3zBAuP6goX3WS8kPT/0WbFKMBMonsuw=,tag:0aptXIOGq3HpS1MZLB4G6w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:AR1aki811QpMj64UhAWLbWg=,iv:kTy1wWEvQvYIjGmYJKK6NFsF4mGLdSH3J3DoQ1sorII=,tag:iBsPSr071LEWjFTakj6RLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVTBNbzVIN3g3N0ZnMFdK
            U0tua1EyUFNhd0tMUy9QS2d1RkFnL0NBc1ZJCnBZRk5VbnlpdGdSYS9yVHBZZmhu
            N2ErZ2NLRTBlcGl3VFdScmp5WnNEYWsKLS0tIHhNMDBTU0VZTWVYczNpRG1nanNi
            Z3hUOEpmeWc1RVZQM2o5cThXR0tvbXcKX55jTjAPD0m6+pGlvSyYOaWqOfkt8Io+
            6zoKngtCuC6/jwGehkfVZBoksYeDWwKGYmPo7U3+dAxcRzi1FKBprw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T14:50:36Z"
    mac: ENC[AES256_GCM,data:9VetlqYVqEiuFeirbUpm3U2OmcoWQj1ROltBkVAATPiRyH6yOYWOvxLeQzrxi51IU7J3jXpA7zeprJ298jjmYamgfJMK/M1CB0T39/urbNuDpOgUcr/FeoJwKNdR0PhI9WggKW2w9rITpqEUo1Qpk8ocErUmp0w7vNMKkC10e5s=,iv:8jv3AOExWRHnHy8D3h8BTt6gBWsJ2j8fRxoTauYvBzA=,tag:/XQzJRye/vpgV1VqAqR+XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
