---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Vienna"
  KUBE_VIP_ADDR: "192.168.5.200"
  METALLB_LB_RANGE: "192.168.5.30-192.168.5.199"
  METALLB_K8S_GATEWAY_ADDR: "192.168.5.30"
  METALLB_INGRESS_ADDR: "192.168.5.31"
