apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:280/7SYZG7Re8uo=,iv:EHpKkW6eKgjO00FBhuAsgQHUMbc73xSFhbKCLEsahp0=,tag:h79IL2rvKw72SG10XNjzew==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:/hWVLS7C7jVweMfIwyXvZZ0=,iv:oAEasQhpDvwq/g+fUCXD0HView7dUPWS4ta8g7lK5eM=,tag:Fqr6Z3cgfyNedwfcR52YOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx782sy3nzw3z45tjwqzlj7c99pauwsu2glz8hdjxnl5dnqk0dns44sg40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVN0xTSTBWd1hicHlMc3lT
            QVBiYklhVENtUVlsNzF1Sy80UEpiRmc0KzBNCjBBOVJBTzREazRrdmM1U0ptVVpI
            VDhIWUNPMGUzZmtVeGIzUWJSYUowOHMKLS0tIEwwS09RMllNeGpzQ2Y2MldhZnRz
            cUZlcFcrbkNablIzRHY2NGFHeVlMM1UK86Bf4hqq82jV2EuCvz5s1R4bUurzxieP
            RJcQVC9UC0O+LEfI1ju+MJsE93UgJdIrHq6jl1EYlsXikepXFow7/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T19:05:26Z"
    mac: ENC[AES256_GCM,data:8B133SB0nMOwXh1g3ItQ84rcr8TWBOGBod1kigvLfZvoWNUu1XcWYYz7/Ro10QqdpMcRBvpIQaWw29HsnBSBJZnKyLJma4Uw+oUzBDvMNgtuANb9TOcUUx+2T9YfGAd5RIyrYAp0zn7+98EAHG+QJzsrubsskWoTR57BnKGWdV8=,iv:8uOsmflXOAgPBm/mdeHJBmG1yEAJoMhLD5vH1FSDjSc=,tag:uK1EZJ4jyO9klRv+EGIvyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
