---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudflare-ddns/ks.yaml
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./metallb/ks.yaml
  - ./traefik/ks.yaml
  - ./homelab-external-services/authelia
  - ./homelab-external-services/bitbucket
  - ./homelab-external-services/bitwarden
  - ./homelab-external-services/confluence
  - ./homelab-external-services/duplicati
  - ./homelab-external-services/getferdi
  - ./homelab-external-services/loxone
  - ./homelab-external-services/nextcloud
  - ./homelab-external-services/plex
  - ./homelab-external-services/unifi
