---
apiVersion: v1
kind: Endpoints
metadata:
  name: duplicati
  namespace: networking
subsets:
  - addresses:
      - ip: 192.168.1.70
    ports:
      - name: duplicati-app
        port: 8200
        protocol: TCP
