---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/traefik/app/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-tls-stores
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-traefik
  path: ./kubernetes/apps/networking/traefik/app/addons/tls-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-tls-options
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-traefik-tls-stores
  path: ./kubernetes/apps/networking/traefik/app/addons/tls-options
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-middlewares
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-traefik-tls-options
  path: ./kubernetes/apps/networking/traefik/app/addons/middlewares
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-traefik-dashboard
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-traefik-middlewares
  path: ./kubernetes/apps/networking/traefik/app/addons/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
