---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
      defaultFsType: xfs
      defaultClassReplicaCount: 3
      reclaimPolicy: Delete
      recurringJobSelector:
        enable: false
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hajimari.io/enable: "true"
        hajimari.io/icon: "server"
        hajimari.io/appName: "longhorn"
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-external-authelia-auth@kubernetescrd"
      host:
        name: "longhorn.${SECRET_DOMAIN}"
        path: /
      tls:
        - secretName: "longhorn.${SECRET_DOMAIN}-tls"
          hosts:
            - "longhorn.${SECRET_DOMAIN}"
    defaultSettings:
      defaultReplicaCount: 3
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      backupTargetCredentialSecret: longhorn-s3-aws-creds
      backupTarget: s3://longhorn@eu-central-1/
      restoreVolumeRecurringJobs: true
      defaultLonghornStaticStorageClass: longhorn
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      orphanAutoDeletion: true
