---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
resources:
  - ./secrets.sops.yaml
  - ./helmrelease.yaml
  - ./storageclass.yaml
