---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia
  namespace: networking
spec:
  forwardAuth:
    address: "http://192.168.1.70:9091/api/verify?rd=https://login.cyberius.at/"
    trustForwardHeader: true
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Groups"
