---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-dav-redirect
  namespace: networking
spec:
  redirectRegex:
    permanent: true
    regex: 'https://(.*)/.well-known/(card|cal)dav'
    replacement: 'https://${1}/remote.php/dav/'
