---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rfc1918-ips
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 192.168.1.0/24
      - 192.168.2.0/24
      - 192.168.3.0/24
      - 192.168.4.0/24
      - 192.168.5.0/24
      - 192.168.6.0/24
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rfc1918
  namespace: networking
spec:
  chain:
    middlewares:
      - name: rfc1918-ips
